restructure to grep failed packages

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -1,7 +1,12 @@
 name: CI
+
 on:
   push:
-  pull_request:
+  #  branches:
+  #    - "master"
+  #    - "develop"
+  # pull_request:
+  #     types: [opened, synchronize, reopened]
 jobs:
   build:
     defaults:
@@ -20,8 +25,8 @@ jobs:
     - name: Checkout ${{ github.event.repository.name }}
       uses: actions/checkout@v3.3.0
       with:
-        fetch-depth: 0
         path: src/${{ github.event.repository.name }}
+        fetch-depth: 0
     - name: Move source code
       run: mv $GITHUB_WORKSPACE/src /opt/carma/
     - name: Checkout dependencies
@@ -38,8 +43,8 @@ jobs:
       continue-on-error: true
       run: |
         source "$INIT_ENV"
-        sed -i '/colcon test/ s/$/ --parallel-workers 4 --packages-above $PACKAGES/' /home/carma/.ci-image/engineering_tools/code_coverage/make_with_coverage.bash
-        make_with_coverage.bash -t -e /opt/carma/ -o ./coverage_reports/gcov   
+        sed -i '/colcon test/ s/$/ --packages-up-to $PACKAGES/' /home/carma/.ci-image/engineering_tools/code_coverage/make_with_coverage.bash
+        make_with_coverage.bash -t -e /opt/carma/ -o ./coverage_reports/gcov || true  # Continue on error
     - name: Backup ROS1 compile_commands.json
       run: |
         mv /opt/carma/build/compile_commands.json /opt/carma/compile_commands.ros1.json        
@@ -51,21 +56,25 @@ jobs:
     - name: Build ROS2
       run: |
         source "$INIT_ENV"
-        source "$ROS_2_ENV" 
+        source "$ROS_2_ENV"
         PACKAGES=$(find . -maxdepth 2 -type f -name package.xml | sed 's/\.\///' | cut -d/ -f1)
-        sed -i '/colcon build/ s/$/ --continue-on-error --parallel-workers 4 --packages-up-to $PACKAGES/' /home/carma/.ci-image/engineering_tools/code_coverage/make_with_coverage.bash
-        make_with_coverage.bash -m -e /opt/carma/ -o ./coverage_reports/gcov        
-    - name: Run ROS2 C++ Tests
+        sed -i '/colcon build/ s/$/ --parallel-workers 4 --packages-up-to $PACKAGES/' /home/carma/.ci-image/engineering_tools/code_coverage/make_with_coverage.bash
+        make_with_coverage.bash -m -e /opt/carma/ -o ./coverage_reports/gcov
+    - name: Run Ros2 C++ Tests
       continue-on-error: true
       run: |
         source "$INIT_ENV"
         source "$ROS_2_ENV"
         sed -i '/colcon test/ s/$/ --parallel-workers 4 --packages-above $PACKAGES/' /home/carma/.ci-image/engineering_tools/code_coverage/make_with_coverage.bash
-        make_with_coverage.bash -t -e /opt/carma/ -o ./coverage_reports/gcov
+        make_with_coverage.bash -t -e /opt/carma/ -o ./coverage_reports/gcov || true  # Continue on error
     - name: Combine ROS1 and ROS2 compile_commands.json files
-      run: |
+      continue-on-error: true
+      run: |   
         mv /opt/carma/build/compile_commands.json /opt/carma/compile_commands.ros2.json
-        jq -s add /opt/carma/compile_commands.ros1.json /opt/carma/compile_commands.ros2.json > /opt/carma/build/compile_commands.json        
+        jq -s add /opt/carma/compile_commands.ros1.json /opt/carma/compile_commands.ros2.json > /opt/carma/build/compile_commands.json       
+    - name: List Failed Packages
+      run: |
+        grep -E -i "Error|Fail" /path/to/your/logfile.log > failed_packages.txt           
     - name: Run SonarScanner
       uses: usdot-fhwa-stol/actions/sonar-scanner@main
       with:
